### PR TITLE
Abstracted installation directories

### PR DESCRIPTION
**Pull request by stevenroose**
Also changed default to /var/www to comply with YunoHost install CD partition table. /var is intended for package installs, while / (which contains /opt) should only contain OS files and is thus kept small.

I installed YunoHost from the USB installation medium and the Gogs installation made the / partition overflow. /var is made large enough because it is intended to contain all app files.

### CODE REVIEW

**Comment by stevenroose** [comment]
Watch out with the one of the nginx file. There is still something wrong, but I couldn't really figure it out last time I looked at it. Perhaps you can fix them, otherwise I might look at it once more this weekend.

**Comment by stevenroose** [comment]
I tried the merge in my fork and you have to be careful with the init.d error.

I'm sure you would notice, but just an extra reminder. It has a conflict that has the old version with the typo fixed or the new version with the typo, so you have to really merge the two snippets ;)

**Comment by stevenroose** [comment]
Does Gogs still install in `/opt`?

**Comment by julienmalik** [comment]
We use /opt/yunohost for a number of other apps running daemon that are reverse-proxified by nginx (ffsync, gplayweb, ghosts, ...). They are installed in /opt/yunohost/$app
According the the Linux FHS, this is the place to put our stuff into (http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s13.html)

**Comment by stevenroose** [comment]
My major concern was the Yunohost ISO that by default created a very tiny
/opt partition. Kload told me the ISO was deprecated though...

**Pull request closed without merging**
